### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by conda-grayskull** [comment]
================ **HOST** ================
Requirements for **host**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| pip | pip | :heavy_check_mark: |
| python >=3.6 | python >=3.6 | :heavy_check_mark: |


================ **RUN** ================
Requirements for **run**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| markdown >=3.2 | markdown >=3.2 | :heavy_check_mark: |
| mkdocs >=1.2.3 | mkdocs >=1.2.3 | :heavy_check_mark: |
| mkdocs-material-extensions >=1.0 | mkdocs-material-extensions >=1.0 | :heavy_check_mark: |
| pygments >=2.10 | pygments >=2.10 | :heavy_check_mark: |
| pymdown-extensions >=9.0 | pymdown-extensions >=9.0 | :heavy_check_mark: |
| python >=3.6 | python >=3.6 | :heavy_check_mark: |
| | jinja2 >=2.11.1 | :heavy_plus_sign: |

**Comment by marcelotrevisani** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by conda-grayskull** [comment]
================ **HOST** ================
Requirements for **host**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| pip | pip | :heavy_check_mark: |
| python >=3.6 | python >=3.6 | :heavy_check_mark: |


================ **RUN** ================
Requirements for **run**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| markdown >=3.2 | markdown >=3.2 | :heavy_check_mark: |
| mkdocs >=1.2.3 | mkdocs >=1.2.3 | :heavy_check_mark: |
| mkdocs-material-extensions >=1.0 | mkdocs-material-extensions >=1.0 | :heavy_check_mark: |
| pygments >=2.10 | pygments >=2.10 | :heavy_check_mark: |
| pymdown-extensions >=9.0 | pymdown-extensions >=9.0 | :heavy_check_mark: |
| python >=3.6 | python >=3.6 | :heavy_check_mark: |
| jinja2 >=2.11.1 | jinja2 >=2.11.1 | :heavy_check_mark: |

**Comment by conda-grayskull** [comment]
Working on your request...

**Pull request merged**
